# Generated by Django 3.2.5 on 2021-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mst',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
