# Generated by Django 3.2.5 on 2021-07-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_user_mst_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mst',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_mst',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user_mst',
            name='updated',
        ),
    ]
